# Generated by Django 3.2.5 on 2021-11-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product_colortranslation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_sizetranslation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcategorytranslation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
