# Generated by Django 3.2.5 on 2021-11-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211108_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.product')),
            ],
        ),
        migrations.RenameModel(
            old_name='Product_color',
            new_name='ProductColor',
        ),
        migrations.RenameModel(
            old_name='Product_sizeTranslation',
            new_name='ProductColorTranslation',
        ),
        migrations.RenameModel(
            old_name='Product_size',
            new_name='ProductSize',
        ),
        migrations.RenameModel(
            old_name='Product_colorTranslation',
            new_name='ProductSizeTranslation',
        ),
        migrations.AlterModelOptions(
            name='productcolortranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'product color Translation'},
        ),
        migrations.AlterModelOptions(
            name='productsizetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'product size Translation'},
        ),
        migrations.AlterModelTable(
            name='productcolortranslation',
            table='store_productcolor_translation',
        ),
        migrations.AlterModelTable(
            name='productsizetranslation',
            table='store_productsize_translation',
        ),
        migrations.DeleteModel(
            name='Product_image',
        ),
    ]
