# Generated by Django 3.2.5 on 2021-11-10 15:29

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211108_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolortranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='store.productcolor'),
        ),
        migrations.AlterField(
            model_name='productsizetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='store.productsize'),
        ),
    ]
