# Generated by Django 3.2.5 on 2021-10-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211028_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availabilty',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.FloatField(default=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
