# Generated by Django 3.2.5 on 2021-10-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211028_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
    ]
