# Generated by Django 3.2.5 on 2021-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='guarantee',
            field=models.CharField(default=2, max_length=255, null=True),
        ),
    ]
