# Generated by Django 3.2.5 on 2021-10-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
    ]
