# Generated by Django 3.2.5 on 2022-01-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('3', 'bepul'), ('1', 'yangi'), ('2', 'ishlatilgan')], default='1', max_length=10, null=True),
        ),
    ]
