# Generated by Django 3.2.5 on 2021-11-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211108_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genders',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gmail',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=10, null=True),
        ),
    ]
