# Generated by Django 3.2.5 on 2021-11-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211108_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], default='m', max_length=10, null=True),
        ),
    ]
