# Generated by Django 3.2.5 on 2021-10-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_genders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genders',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=10),
        ),
    ]
