# Generated by Django 3.2.5 on 2021-11-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_genders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genders',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], default='m', max_length=10),
        ),
    ]
