# Generated by Django 3.2.5 on 2021-12-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='account',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
