# Generated by Django 3.2.5 on 2021-12-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_auto_20211204_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
