# Generated by Django 3.2.5 on 2021-12-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_auto_20211222_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='client',
            new_name='user',
        ),
    ]
