# Generated by Django 3.2.5 on 2021-12-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_rename_client_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
