# Generated by Django 3.2.5 on 2021-12-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0011_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
    ]
