# Generated by Django 3.2.5 on 2021-08-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleforms', '0003_auto_20210812_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
