# Generated by Django 3.2.5 on 2021-11-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupongroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
