# Generated by Django 3.2.5 on 2021-11-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_cupongroup_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupongroup',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='cupon',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
