# Generated by Django 3.2.5 on 2021-08-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_cupon_cupongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='is_used',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
