# Generated by Django 3.2.5 on 2021-11-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20211101_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
    ]
