# Generated by Django 3.2.5 on 2021-11-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_remove_wishlist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
