# Generated by Django 3.2.5 on 2021-11-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_wishlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='status',
        ),
    ]
